// <auto-generated />
using System;
using GerenteAutoestima.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GerenteAutoestima.Migrations
{
    [DbContext(typeof(GerenteAutoestimaContext))]
    [Migration("20190527145052_ProdutoEntity")]
    partial class ProdutoEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GerenteAutoestima.Models.CategoriaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("CategoriaProduto");
                });

            modelBuilder.Entity("GerenteAutoestima.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoriaProdutoId");

                    b.Property<string>("Nome");

                    b.Property<double>("Preco");

                    b.Property<int>("QuantidadeDisponivel");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProdutoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("GerenteAutoestima.Models.Produto", b =>
                {
                    b.HasOne("GerenteAutoestima.Models.CategoriaProduto", "CategoriaProduto")
                        .WithMany("produtos")
                        .HasForeignKey("CategoriaProdutoId");
                });
#pragma warning restore 612, 618
        }
    }
}
